### ISSUE TITLE
etcd的delete事件没法回调，貌似atproxy_manager事件不依赖delete事件？

### ISSUE THREAD

**Issue by tangzhenquan** [atframework/atsf4g-co#2]
https://github.com/atframework/atsf4g-co/blob/fc14114ca2d7577999cc98344ff758f561cbe12a/atframework/service/component/modules/etcd_module.cpp#L867-L875

**Comment by owent** [comment]
@tangzhenquan 有回调呀
https://github.com/atframework/atsf4g-co/blob/master/atframework/service/atproxy/atproxy_manager.cpp#L234

**Comment by tangzhenquan** [comment]
https://github.com/atframework/atsf4g-co/blob/fc14114ca2d7577999cc98344ff758f561cbe12a/atframework/service/component/modules/etcd_module.cpp#L700-L712
我是说当delete事件时unpack始终是返回false，相当与没法回调，但是atproxy_manager能成功运行，说明更依赖连接的断开而不依赖这个delete事件。

**Comment by owent** [comment]
@tangzhenquan 这里只是个fallback，因为存的时候path的最后一段也是id。这里返回只是说是不是从json里解析出来的完整信息。还是走的fallback从path里解析出来的部分数据。删除事件只需要知道id就行了。

**Comment by tangzhenquan** [comment]
@owt5008137 关键是etcd的delete事件只会带路径，不会带值，所以evt_data.kv.value是空，那么所有的只要etcd的是delete事件 if (!unpack(node, evt_data.kv.key, evt_data.kv.value, true)) { 
     continue; 
 }就是continue了，这时跟预期是不符合的，代码不会往下走了，if (evt_data.evt_type == ::atframe::component::etcd_watch_event::EN_WEVT_DELETE) { 
     node.action = node_action_t::EN_NAT_DELETE; 
 } else { 
     node.action = node_action_t::EN_NAT_PUT; 
 } 这一块代码不会再执行了，感觉是个bug吧

**Comment by owent** [comment]
@tangzhenquan 这里确实有问题。这个是近期加的多个watch的功能重构得有点问题。遗漏DELETE事件会导致如果缩容的话（就是这个atproxy不会再被拉起）atproxy不断尝试去连接那个DELETE掉的节点。虽然不会影响正常通信但是会有脏数据和浪费资源。
如果同id得atproxy再被拉起得话，新数据会覆盖旧的就会把脏数据修复掉。

我先简单修复了下，这个我会和后面一波其他的功能更新一起测一下。
